import Head from 'next/head';
import React from 'react'

export default function about() {
  return (
      <>
      <Head>
        <title className='text-w'>E-commerce by Azmi - nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>about</div>
      </>
  )
}
