import Head from "next/head";
import Hero from "../components/Hero";
import ProductsSection from "../components/ProductsSection";
import ProductCategoriesSection from "../components/ProductCategoriesSection";
import db from "../utils/db";
import { API_BASE_URL } from "../config";
import dynamic from "next/dynamic";
import { wrapper } from "../store/store";

const Layout = dynamic(() => import("../components/Layout"), {
  ssr: false,
});
export default function Home(props) {
  const { products, categories } = props;
  return (
    <>
      <Head>
        <title className="text-w">E-commerce by Azmi - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout categories={categories}>
        <Hero />
        <ProductCategoriesSection categories={categories} />
        <ProductsSection
          products={products}
          heading="Fresh New Products"
          tagline=""
        />
      </Layout>
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    const productRes = await fetch(API_BASE_URL + "/products");
    const products = await productRes.json();

    // All Categories API
    const categoriesRes = await fetch(API_BASE_URL + "/categories");
    const categories = await categoriesRes.json();

    return {
      props: {
        products: products.map(db.convertDocToObj),
        categories: categories.map(db.convertDocToObj),
      },
    };
  }
);
